services:
  lumaapi:
    image: lumaapi/luma-api:latest
    container_name: luma-api
    restart: unless-stopped
    ports:
      - "7748:8000"
    volumes:
      - ./logs:/logs
    env_file:
      - .env