version: '3'

services:
  ninja:
    image: gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    #  - PROXIES=${PROXIES}
      - ENABLE_ARKOSE_PROXY=true  
    #command: run -L info --arkose-solver fcsrv --arkose-solver-key my-arkose-fcsrv --arkose-solver-endpoint http://107.173.244.51:8000/task  --arkose-solver-image-dir /aimg # ${ARKOSE_SOLVER_KEY} --no-keepalive 如果是只做arkose 可以不开启 这样更不消耗验证码
    command: run -L info --arkose-solver=yescaptcha --arkose-solver-key=${ARKOSE_SOLVER_KEY}  --arkose-endpoint http://107.173.244.51:7999   # ${ARKOSE_SOLVER_KEY} --no-keepalive 如果是只做arkose 可以不开启 这样更不消耗验证码
    ports:
      - "7999:7999"
    volumes:
      - "~/.ninja:/root/.ninja"
      - "./aimg:/aimg"
  #   depends_on:
  #     - fcsrv
  # fcsrv:
  #   image: ghcr.io/gngpp/fcsrv:latest
  #   container_name: fcsrv
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Asia/Shanghai
  #   command: run --model-dir /models -A my-arkose-fcsrv
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - "./models:/models"