version: '3'

services:
  ninja:
    image: gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PROXIES=${PROXIES}
      - ENABLE_ARKOSE_PROXY=true  
    command: run -L info --arkose-solver=yescaptcha --arkose-solver-key=${ARKOSE_SOLVER_KEY} # --no-keepalive 如果是只做arkose 可以不开启 这样更不消耗验证码
    ports:
      - "7999:7999"
    volumes:
      - "~/.ninja:/root/.ninja"
  fcsrv:
    image: ghcr.io/gngpp/fcsrv:latest
    container_name: fcsrv
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    command: run --model-dir /models
    ports:
      - "8000:8000"
    volumes:
      - "./models:/models"