version: '3'

services:
  ninja:
    image: gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      #- PROXIES=http://107.181.187.120:10075,http://107.181.187.120:10076,http://107.181.187.120:10077,http://107.181.187.120:10078,http://107.181.187.120:10079,http://107.181.187.120:10111,http://107.181.187.120:10112,http://107.181.187.120:10113,http://107.181.187.120:10114,http://107.181.187.120:10115
      #- PROXIES=socks5://43.159.29.44:20177
      #- PROXIES=all|http://43.159.29.44:20177
      
    command: run -L info --arkose-solver=yescaptcha --arkose-solver-key=2beaeaeb43e7dddfec1a64922e1fa4fcbb8ea2a831961 
    ports:
      - "7999:7999"
    volumes:
      - "~/.ninja:/root/.ninja"
      # - "./har/gpt3:/root/.ninja/gpt3"
      # - "./har/gpt4:/root/.ninja/gpt4"
      # - "./har/auth:/root/.ninja/auth"
      # - "./har/platform:/root/.ninja/platform"
      # - "./har/signup:/root/.ninja/signup"
  #   depends_on:
  #     - warp

  # warp:
  #   container_name: warp
  #   image: ghcr.io/gngpp/warp:latest
  #   restart: unless-stopped
  #command: run  --disable-webui --arkose-solver=yescaptcha --arkose-solver-key=2beaeaeb43e7dddfec1a64922e1fa4fcbb8ea2a831961