version: '3'

services:
  ninja:
    image: gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PROXIES=all|http://43.159.29.44:20177
      # - PROXIES=socks5://warp:10000
      
    command: run -L info --arkose-solver=yescaptcha --arkose-solver-key=2beaeaeb43e7dddfec1a64922e1fa4fcbb8ea2a831961
    ports:
      - "7999:7999"
    volumes:
      - "./har/gpt3:/root/.ninja/gpt3"
      - "./har/gpt4:/root/.ninja/gpt4"
      - "./har/auth:/root/.ninja/auth"
      - "./har/platform:/root/.ninja/platform"
      - "./har/signup:/root/.ninja/signup"
  #   depends_on:
  #     - warp

  # warp:
  #   container_name: warp
  #   image: ghcr.io/gngpp/warp:latest
  #   restart: unless-stopped
  #command: run  --disable-webui --arkose-solver=yescaptcha --arkose-solver-key=2beaeaeb43e7dddfec1a64922e1fa4fcbb8ea2a831961