version: '3'
services:
  addmao:
    image: ydlhero/chatgpt-web-midjourney-proxy:latest 
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      OPENAI_API_KEY: ${MAP_API_KEY}
      OPENAI_API_BASE_URL: ${MAO_BASE_URL}
      MJ_SERVER: https://api.openai.com
      MJ_API_SECRET: abc123456
      TJ_BAIDU_ID: 9d5fa7fc2f5fd585aa8fd3010d19be1e
      SYS_NOTIFY: "<div style='text-align: left'>1.本站仅支持GPT-3.5序列<br>2.如果您需要使用GPTs,GPT-4,midjourney画图等模型 可以点击<a href='https://www.openai-hk.com/docs/openai/api-key.html'>这里获取apiKey</a></div>"
    ports:
      - "8015:3002" #管理端口
  
  ddcici:
    image: ydlhero/chatgpt-web-midjourney-proxy:latest 
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      OPENAI_API_KEY: hk-sdsdsd
      OPENAI_API_BASE_URL: https://api.openai.com
      MJ_SERVER: https://api.openai.com
      MJ_API_SECRET: abc123456
      TJ_BAIDU_ID: 9d5fa7fc2f5fd585aa8fd3010d19be1e
    ports:
      - "2015:3002" #管理端口
