version: '3'
services:
  addmao:
    image: ydlhero/chatgpt-web-midjourney-proxy:latest 
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      OPENAI_API_KEY: ${MAP_API_KEY}
      OPENAI_API_BASE_URL: ${MAO_BASE_URL}
      MJ_SERVER: https://api.openai.com
      MJ_API_SECRET: abc123456
      TJ_BAIDU_ID: 9d5fa7fc2f5fd585aa8fd3010d19be1e
      VISION_MODEL: gpt-4o
      SYS_NOTIFY: "<div style='text-align: left'>1.近日有不法分子利用本站行非法之事，故先暂停本站服务,8月15后再考虑是否恢复<br>2.本站仅是一个纯公益站点；请勿滥用<br>3.请收藏本站地址 <a href='https://free.addmao.com' target='_blank' style='color:#4b9e5f ;text-decoration: underline'>free.addmao.com</a><br>4.合作等其他事务请邮件联系 help@addmai.com </div>"
      # TURNSTILE_SITE: 0x4AAAAAAAVOQiP6eh3vOjeJ
      # TURNSTILE_SECRET_KEY: 0x4AAAAAAAVOQujn0yxvkh2g30I4aMIthwE
      #TURNSTILE_NO_CHECK: 1
    ports:
      - "8015:3002" #管理端口
  # addmao-ru:
  #   image: ydlhero/chatgpt-web-midjourney-proxy:latest 
  #   restart: unless-stopped
  #   environment:
  #     TZ: Asia/Shanghai # 指定时区
  #     OPENAI_API_KEY: ${MAP_API_KEY}
  #     OPENAI_API_BASE_URL: ${MAO_BASE_URL}
  #     MJ_SERVER: https://api.openai.com
  #     MJ_API_SECRET: abc123456
  #     TJ_BAIDU_ID: 9d5fa7fc2f5fd585aa8fd3010d19be1e
  #     SYS_NOTIFY: "<div style='text-align: left'>1.Этот сайт поддерживает только последовательности GPT-3.5<br>2.Если вам нужно использовать GPTs, GPT-4, midjourney и другие модели, вы можете нажать <a href='https://www.openai-hk.com/docs/openai/api-key.html' target='_blank' style='color:Red ;text-decoration: underline'>Получите apiKey здесь.</a> <br>3.Чтобы не заблудиться, добавьте в закладки наш сайт <a href='https://ru.addmao.com' target='_blank' style='color:#4b9e5f ;text-decoration: underline'>ru.addmao.com</div>"
  #     # TURNSTILE_SITE: 0x4AAAAAAAVOQiP6eh3vOjeJ
  #     # TURNSTILE_SECRET_KEY: 0x4AAAAAAAVOQujn0yxvkh2g30I4aMIthwE
  #     #TURNSTILE_NO_CHECK: 1
  #   ports:
  #     - "8016:3002" #管理端口
  next-web:
    profiles: [ "no-proxy" ]
    container_name: next-web
    image: yidadaa/chatgpt-next-web
    ports:
      - 6043:3000
    environment:
      TZ: Asia/Shanghai # 指定时区
      ENABLE_BALANCE_QUERY: 1
  ddcici:
    image: ydlhero/chatgpt-web-midjourney-proxy:latest 
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      OPENAI_API_KEY: hk-sdsdsd
      OPENAI_API_BASE_URL: https://api.openai.com
      MJ_SERVER: https://api.openai.com
      MJ_API_SECRET: abc123456
      TJ_BAIDU_ID: 9d5fa7fc2f5fd585aa8fd3010d19be1e
    ports:
      - "2015:3002" #管理端口

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "7076:3001" #管理端口
    volumes:
      - "./uptime-kuma:/app/data"