services:
  hx:
    image: ydlhero/nxgod
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "9022:9011" #管理端口
      - "3001:3001" #audio 现场生成
    volumes:
      - ./log/supervisor:/var/log/supervisor

  openresty:
    image: openresty/openresty:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/real.com.conf:/etc/nginx/conf.d/real.com.conf:ro
      - ./config/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./config/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./log/nginx:/var/log/nginx
    depends_on:
      - hx
    environment:
      TZ: Asia/Shanghai
