version: '3'
services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "6028:6001" #管理端口
      - "3800:6000" #业务端口 
      - "6022:6022" #ssh n3
      - "6023:6023" #ssh n5 
      - "6021:6021" #ssh n2
      - "6024:6024" #windows
      - "6025:6025" # ipv4 proxy
      - "6088:6088" # github.com 22
    volumes:
      - ./config:/usr/local/etc/haproxy:ro
