version: '3'
services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "6028:6001" #管理端口
      - "3800:6000" #业务端口 
    volumes:
      - ./config:/usr/local/etc/haproxy:ro
