version: '3'
services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "6001:6001" #管理端口
      - "6000:6000" #管理端口
      - "443:443" #https
      - "80:80" #  http
