services:
  app:
    image: ghcr.io/aurora-develop/aurora:latest
    container_name: aurora
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      PROXY_URL: {$PROXY_URL}
    ports:
      - '7080:8080'  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "7001:6001" #管理端口
      - "7000:6000" #业务端口
    volumes:
      - ./config:/usr/local/etc/haproxy:ro