services:
  app:
    image: ghcr.io/aurora-develop/aurora:latest
    container_name: aurora
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      PROXY_URL: ${PROXY_URL}
    ports:
      - '7080:8080'  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "7001:6001" #管理端口
      - "7000:6000" #业务端口
      - "5999:5999" #业务端口
    volumes:
      - ./config:/usr/local/etc/haproxy:ro
  
  chat2api:
    image: lanqian528/chat2api:latest
    #container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    environment:
      #- AUTHORIZATION=your_first_token, your_second_token
      - AUTHORIZATION=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJzZXNzaW9uX2lkIjoiYWtjZUhYV2FxblZMR2ZuSGpjTG53cFJYOWlCTjQ3MHkiLCJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ3YW5nbmFhaWxnQGhvdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsicG9pZCI6Im9yZy1wb3NTUEFsZmtrWURyWnhxc0V0WHhMNksiLCJ1c2VyX2lkIjoidXNlci1ZRVdUVm9wTWlGcnRDZDI2VHJzQ21GTDQifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDY1YWZhNjMwZGUwMGRhYTlmMzE1YWM1MiIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTQ0NDQ3NTUsImV4cCI6MTcxNTMwODc1NSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb3JnYW5pemF0aW9uLndyaXRlIG9mZmxpbmVfYWNjZXNzIiwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEcifQ.fX4VY7GfFbZVInwLufJ_weIcogc7CxnUINJ9Q-zEjG7ukcUv9tYjr4fXIYx_UMOIeV2QrxLr26RefRkkR94GHYiUETWObwGxHMdGrYmthMAFbHb0uoI6htDZ08yfDCn_WswTNKPz1xNoQ3bvgUxi6-tCWRxG-eUoeiVsDP4EOxTx8aVV8G2yzcl6jP7vbwuFCF9FHOnfTuEuGDz5ErnJIPk1y-PL7g7Vit8FeGRp-gGG7qFkCufRk4QyO1HZgM9eeUIxE7Zv9fmj6ilOZcIv2b704SKGO6OjhW1ThBLBNAVnWC6mM7Q_YrDL80VAl18bDWEpIi5mEtd5MPCLKL8U4w
#      - CHATGPT_BASE_URL=https://chat.openai.com
#      - HISTORY_DISABLED=true
#      - PROXY_URL=your_first_proxy, your_second_proxy
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
#      - RETRY_TIMES=3
  arkose:
    image: lanqian528/funcaptcha_solver:latest
    #container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
    environment:
      - VERSION=2.4.5
      - HASH=6c9d6e9be9aa044cc5ce9548b4abe1b0