services:
  app:
    image: ghcr.io/aurora-develop/aurora:latest
    container_name: aurora
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      PROXY_URL: ${PROXY_URL}
    ports:
      - '7080:8080'  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "7001:6001" #管理端口
      - "7000:6000" #业务端口
      - "5999:5999" #业务端口
    volumes:
      - ./config:/usr/local/etc/haproxy:ro
  
  chat2api:
    image: lanqian528/chat2api:latest
    #container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    environment:
      #- AUTHORIZATION=your_first_token, your_second_token
      - AUTHORIZATION=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJlbGJ1cmFidmExOTgwQGhvdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsicG9pZCI6Im9yZy1tS0tWU3U2eHFoV0UzZVp2cGZKRjBLOHUiLCJ1c2VyX2lkIjoidXNlci1RQmZqcXA3MjBaa09NNlpGNGNTNDJFUXUifSwicHdkX2F1dGhfdGltZSI6MTcxMzkyNjE4MDIyNywiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDY2MThiYWQ4OGE0NTllOTY5MjU5NmU3ZCIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTM5MjYxODMsImV4cCI6MTcxNDc5MDE4Mywic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb3JnYW5pemF0aW9uLndyaXRlIG9mZmxpbmVfYWNjZXNzIiwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEcifQ.K-K7Fe1sAQn8Ug6p3JnOgVkgmukKpMRzFXOW7RHEJmU5YNLPHpoO1q232604LwDCACZKxlXSfKfnTuf8XaQu2p8PebjQmOrgEtRR7VvpVYUyH_abDpU8GjIKQPrNOLGGHcTuskCHH4KBILpp2U5wNyUMkl42shu3pIGvH7a4ikJPmyfsmUSGwK7KwNJz0sRlAYn2BxgyXlXEJzz7eM5sU5Q66yx11z6yM5xl_VgP8mHzpnP55jLDMQjNWoSQ1fX_FNaVVhcIMTXKuDHy_J5GrFYyY8l6VmdMoNO4w_BQsvCdK_hi1gUaE0IlU7_1AVy80o_jI_Ybs3iBczUgqLsd8g
#      - CHATGPT_BASE_URL=https://chat.openai.com
#      - HISTORY_DISABLED=true
#      - PROXY_URL=your_first_proxy, your_second_proxy
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
#      - RETRY_TIMES=3
  arkose:
    image: lanqian528/funcaptcha_solver:latest
    #container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
    environment:
      - VERSION=2.4.5
      - HASH=6c9d6e9be9aa044cc5ce9548b4abe1b0