services:
  app:
    image: ghcr.io/aurora-develop/aurora:latest
    container_name: aurora
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      PROXY_URL: ${PROXY_URL}
    ports:
      - '7080:8080'  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "7001:6001" #管理端口
      - "7000:6000" #业务端口
      - "5999:5999" #业务端口
    volumes:
      - ./config:/usr/local/etc/haproxy:ro
  
  chat2api:
    image: lanqian528/chat2api:latest
    #container_name: chat2api
    restart: unless-stopped
    ports:
      - '4005:5005'
    environment:
      #- AUTHORIZATION=your_first_token, your_second_token
#      - CHATGPT_BASE_URL=https://chat.openai.com
#      - HISTORY_DISABLED=true
      - PROXY_URL=${PROXY_URL2}
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
      - RETRY_TIMES=1
  
  chat3api:
    image: lanqian528/chat2api:latest 
    restart: unless-stopped
    ports:
      - '4004:5005'
    environment:
      #- AUTHORIZATION=your_first_token, your_second_token
      - CHATGPT_BASE_URL=https://chat.oaifree.com/dad04481-fa3f-494e-b90c-b822128073e5
#      - HISTORY_DISABLED=true
      #- PROXY_URL=${PROXY_URL4}
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
      - RETRY_TIMES=3

  arkose:
    image: lanqian528/funcaptcha_solver:latest
    #container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
    environment:
      - VERSION=2.4.5
      - HASH=6c9d6e9be9aa044cc5ce9548b4abe1b0