services:
  app:
    image: ghcr.io/aurora-develop/aurora:latest
    container_name: aurora
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
      PROXY_URL: ${PROXY_URL}
    ports:
      - '7080:8080'  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "7001:6001" #管理端口
      - "7000:6000" #业务端口
      - "5999:5999" #业务端口
    volumes:
      - ./config:/usr/local/etc/haproxy:ro
  
  chat2api:
    image: lanqian528/chat2api:latest
    #container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    environment:
      #- AUTHORIZATION=your_first_token, your_second_token
      - AUTHORIZATION=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ3YW5nbmFhaWxnQGhvdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsicG9pZCI6Im9yZy1wb3NTUEFsZmtrWURyWnhxc0V0WHhMNksiLCJ1c2VyX2lkIjoidXNlci1ZRVdUVm9wTWlGcnRDZDI2VHJzQ21GTDQifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDY1YWZhNjMwZGUwMGRhYTlmMzE1YWM1MiIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTQ0Mjc4MjEsImV4cCI6MTcxNTI5MTgyMSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MiLCJhenAiOiJwZGxMSVgyWTcyTUlsMnJoTGhURTlWVjliTjkwNWtCaCJ9.cgQGoYb9sh6BrWhJR4sIIr5OGEz8NkBxc7JRoCGPHIJsUueGhD5sXBYYEaPCwkMVQpTU0myupd2jSJROMIuMn07rjqxVCIuQYPMCuiExL4xYjCeeCv98s7pbWl5O7kVxKuKu_s_8bK1abMNdMRKxfwJQnKasBcCCYXhW_Hjb_XiZ3YvERWzY8-BkLBJ0Oa5Ia0Y7KEJodSrOaDxrQfS32C0YxDJtdtl5LjhgqVGvvgsibGGYTXbNo4grbXsnJ0eQl6FQ7fbfTyIcfTdoOLa95Nfp0qaB_z0KPwSbEy1RMkbmVOzo2GfEjermAcN5PY5wpcqAWoBozptvEsAVywI6AA
#      - CHATGPT_BASE_URL=https://chat.openai.com
#      - HISTORY_DISABLED=true
#      - PROXY_URL=your_first_proxy, your_second_proxy
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
#      - RETRY_TIMES=3
  arkose:
    image: lanqian528/funcaptcha_solver:latest
    #container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
    environment:
      - VERSION=2.4.5
      - HASH=6c9d6e9be9aa044cc5ce9548b4abe1b0