version: '3'
services:
  myone:
    image: ydlhero/myone:latest
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "6026:3000" #管理端口
    volumes:
      - ./one-api:/data #root cikuutest!
