version: '3'
services:
  myone:
    image: ydlhero/myone:latest
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
      SERVER_TYPE: master #主服务器
    ports:
      - "7026:3000" #管理端口
    volumes:
      - ./one-api:/data 
  gpts2:
    image: ydlhero/myone:latest
    restart: always
    environment:
      #TZ: Asia/Shanghai # 指定时区
      - SQL_DSN=root:tool2024@tcp(172.17.0.1:3306)/oneapi_gpts2
      - TZ=Asia/Shanghai
    ports:
      - "7027:3000" #管理端口
    volumes:
      - ./gpts2:/data #SERVER_TYPE
