services:
  myone:
    image: ydlhero/myone:20240327113551
    restart: always
    environment:
      - TZ=Asia/Shanghai # 指定时区
      - SQL_DSN=root:123456@tcp(172.17.0.1:3360)/oneapi_my
      #SERVER_TYPE: master #主服务器
    ports:
      - "7026:3000" #管理端口
    volumes:
      - ./one-api:/data 
  gpts2: #gpt2.ccaiai.com 支持 suno ，channels 需要单独处理； ALTER TABLE `channels` CHANGE `key` `key` VARCHAR(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
    image: ydlhero/myone:20240410120632
    restart: always
    environment:
      #TZ: Asia/Shanghai # 指定时区
      - SQL_DSN=root:123456@tcp(172.17.0.1:3360)/oneapi_gpts2
      - TZ=Asia/Shanghai
    ports:
      - "7027:3000" #管理端口
    volumes:
      - ./gpts2:/data #SERVER_TYPE
