version: '3'
services:
  fileserver:
    image: ydlhero/file-server:latest
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
      SERVER_NAME: https://file.openai-hk.com:4443
      #SERVER_NAME: https://file.openai-hk.com:4443
    ports:
      - "3102:3102"
    volumes:
      - /data/uploads:/app/uploads
  openresty:
    image: openresty/openresty:latest
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - /data/uploads:/data/uploads
      #- ./certs:/app/certs
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "4443:443"
  