version: '3'
services:
  warp:
    image: hts999/warp-gpt:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      proxy: ${PROXY_URL}
      port: 6050
      host: "0.0.0.0" 
      verify: false
      auth_key: ""
      arkose_must: false
      openai_host: "chat.openai.com"
      openai_api_host: "api.openai.com"
      proxy_pool_url: ""
      log_level: "debug"
      redis_address: "127.0.0.1:6379"
      redis_passwd: ""
      redis_db: 0
    ports:
      - "6050:6050"
  ja3-proxy:
    image: xyhelper/ja3-proxy
    ports:
      - "16524:16524"
      - "7988:9988"
    environment:
      WEBSITE_URL: "https://chat.openai.com/auth/login" # 要过盾的目标网站
      PROXY: ${PROXY_URL} # 代理服务器信息
      CLIENTKEY: ${CLIENT_KEY} # yescaptcha 的 clientKey
      LOCALPROXYUSER: ${LOCALPROXY_USER} # ja3代理服务用户名
      LOCALPROXYPASS: ${LOCALPROXY_PASS} # ja3代理服务密码



