version: '3'
services:
  # chatpoint:
  #   image: ydlhero/chatpoint:latest
  #   restart: always
  #   environment:
  #     TZ: Asia/Shanghai # 指定时区
  #   ports:
  #     - "8091:8091" #chat.openai.com
  #     - "8092:8092" #真的接入点
  #     - "8099:8099" #api.openai.com
  #     - "8100:8100" #https://generativelanguage.googleapis.com
  nginx:
    #container_name: nginx
    image: nginx:alpine
    expose:
      - '80'
    volumes:
      #- ./nginx/html:/usr/share/nginx/html
      - ./conf/:/etc/nginx/conf.d/
    ports:
      - "8091:8091" #chatgpt.com
      - "8092:8092" #真的接入点
      - "8099:8099" #api.openai.com
      - "8100:8100" #https://generativelanguage.googleapis.com
      - "8101:8101" #https://oaifree
    