services:
  gptweb:
    image: ydlhero/chatgpt-web-midjourney-proxy:latest
    restart: always
    environment:
      #你的OPENAI key 比如 hk-xxxxxx 或者 sk-xxxxxx 非中文
      OPENAI_API_KEY: hk-xxx
      OPENAI_API_BASE_URL: https://api.openai-hk.com
      MJ_SERVER: https://api.openai-hk.com
      #你的 MJ API Secret 比如 hk-xxxxxx 或者 sk-xxxxxx 非中文
      MJ_API_SECRET: hk-xxx
      HIDE_SERVER: 1
      API_UPLOADER: 1
      MJ_API_GALLERY: 1
      AUTH_SECRET_ERROR_COUNT: 3
      AUTH_SECRET_ERROR_TIME: 10
      #你的密码 必须由英文或者数字或者下划线组成 （不能用中文）
      AUTH_SECRET_KEY: 访问密码
      FILE_SERVER: http://up.openai-hk.com:3102/v1/upload
    ports:
      - "6080:3002"
    volumes:
      - /data/mj_uploads:/app/uploads
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile
      - ./data/site:/srv
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
